cls
SET db=z:\IM\bctdb.sdb
SET bctfolder=z:\IM
REM ~ ..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq z:\IM\CT|1||2 4|\CTi\CT|2 4|_|3 2|.0001" > _RAID_bctviewer.bat
REM ~ ..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq  -filetype:raw -x:512 -y:512 -datatype:char z:\IM\CT|1||2 4|\SEG\SEG|2 4|_|3 2|_0001.raw" > _RAID_bctsegviewer.bat
REM ~ ..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq -maxseqnum:50 z:\IM\CT|1||2 4|\CTi\CT|2 4|_|3 2|.0001" > _RAID_bctviewer.bat
REM ~ ..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq  -maxseqnum:50 -filetype:raw -x:512 -y:512 -datatype:char z:\IM\CT|1||2 4|\SEG\SEG|2 4|_|3 2|_0001.raw" > _RAID_bctsegviewer.bat

..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 AND r_hassegmentation=1 AND r_segmentationvalid=1 AND ps_contrast=0 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq  -maxseqnum:50 -filetype:raw -x:512 -y:512 -datatype:char z:\IM\CT|1||2 4|\SEG\SEG|2 4|_|3 2|_0001.raw" > _RAID_validsegviewer.bat
..\..\bin\bctdbreader %db% "SELECT s_scannertag,s_id,r_series,r_nx FROM scan JOIN recon ON r_scanid=s_id JOIN patientscan ON ps_scanid=s_id WHERE s_numslices>60 AND r_nx<1000 AND r_hassegmentation=1 AND r_segmentationvalid=0 AND ps_contrast=0 GROUP BY s_id HAVING max(r_series) ORDER BY s_id DESC" "..\..\bin\imageviewer -seq  -maxseqnum:50 -filetype:raw -x:512 -y:512 -datatype:char z:\IM\CT|1||2 4|\SEG\SEG|2 4|_|3 2|_0001.raw" > _RAID_badsegviewer.bat
